# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = moar_brainz.out
SRCS = main.cpp Zombie.cpp zombieHorde.cpp

include ../template.mk

main.cpp Zombie.cpp zombieHorde.cpp: Zombie.hpp
