# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = violence.out
SRCS = main.cpp Weapon.cpp HumanA.cpp HumanB.cpp

include ../template.mk

main.cpp: Weapon.hpp HumanA.hpp
Weapon.cpp: Weapon.hpp
HumanA.cpp: HumanA.hpp
HumanB.cpp: HumanB.hpp
