# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = brainz.out
SRCS = main.cpp Zombie.cpp newZombie.cpp randomChump.cpp

include ../template.mk

main.cpp Zombie.cpp newZombie.cpp randomChump.cpp: Zombie.hpp
